### ISSUE TITLE
db is not defined...but when it is, it's attempting to open an unclosed connection...

### ISSUE THREAD

**Issue by Alexandroidd** [Alexandroidd/ProjectTwo#1]
Cant' seem to get one of my controllers to access my database...

http://stackoverflow.com/questions/7104474/how-does-asynchronous-javascript-execution-happen-and-when-not-to-use-return-st/7104633#7104633

http://stackoverflow.com/questions/34566049/express-js-mongodb-referenceerror-db-is-not-defined-when-db-is-mentioned-out

**Comment by ZebGirouard** [comment]
Ah, the ol' error-behind-another-error.  This looks all set now.
