### ISSUE TITLE
Can't get onto Heroku

### ISSUE THREAD

**Issue by Alexandroidd** [Alexandroidd/ProjectTwo#2]
heroku won't upload:
•pretty sure its my package.json file

-defined my node and npm engines in my package.json
-changed the name of my start file from app.js to server.js
-updated node and npm, still doesn't like either really.
-made a .env file and ignored all the right stuff.

https://github.com/NodeBB/NodeBB/issues/2131
https://github.com/parse-community/parse-server/issues/1589

**Comment by ZebGirouard** [comment]
This is all set, now onto Mongo issues :)
